version: '3'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "8432:5432"
    networks:
      - webnet

  backend:
    build: .
    container_name: backend
    environment:
      - NODE=production
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - webnet

networks:
  webnet:
    driver: bridge